# Generated by Django 3.2.9 on 2022-05-20 08:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='project_specific_details',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
