# Generated by Django 3.2.9 on 2022-06-27 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Con_comment',
        ),
    ]
