# Generated by Django 3.2.9 on 2022-06-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0003_alter_buyerrequest_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyerrequest',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterField(
            model_name='buyerrequest',
            name='body',
            field=models.TextField(verbose_name='Requesting'),
        ),
    ]
