# Generated by Django 3.2.9 on 2022-06-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0004_auto_20220611_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerrequest',
            name='pic',
            field=models.ImageField(blank=True, default='stories/default.png', upload_to='stories'),
        ),
    ]
