# Generated by Django 3.2.9 on 2022-06-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0005_buyerrequest_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerrequest',
            name='pic',
            field=models.ImageField(blank=True, default='stories/default.png', upload_to='stories/'),
        ),
    ]
